# Generated by Django 3.0.2 on 2020-05-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='created',
            new_name='created_on',
        ),
    ]
