# Generated by Django 3.0.2 on 2020-05-24 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0005_auto_20200524_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='part',
            field=models.CharField(choices=[('1', 'PART 1'), ('2', 'PART 2'), ('3', 'PART 3'), ('4', 'PART 4'), ('5', 'PART 5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
