# Generated by Django 3.0.2 on 2020-05-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_auto_20200524_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='user',
            new_name='owner',
        ),
    ]
