# Generated by Django 2.2.13 on 2020-07-17 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_lead_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='owner',
        ),
    ]
